### 회원가입
POST http://localhost:8080/member
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678",
  "nickname": "tester"
}

### 로그인
POST http://localhost:8080/authCustom/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

### 로그인 사용자 확인
GET http://localhost:8080/authCustom/me

###

### 로그아웃
POST http://localhost:8080/authCustom/logout

### 게시글 생성
POST http://localhost:8080/post
Content-Type: application/json

{
  "title": "첫 번째 게시글",
  "content": "게시글 작성 테스트입니다."
}

### 게시글 단건 조회
GET http://localhost:8080/post/detail/1




### 생성
POST http://localhost:8080/todo
Content-Type: application/json

{
  "title": "자바 공부하기"
}


### Todo 단건 조회 성공
GET http://localhost:8080/todo/1

### Todo 단건 조회 실패 - 없는 id
GET http://localhost:8080/todo/999

### Todo 생성
POST http://localhost:8080/todo
Content-Type: application/json

{
  "title": "자바 테스트2"
}

### Todo 수정 - title만 변경
PATCH http://localhost:8080/todo/1
Content-Type: application/json

{
  "title": "Spring 공부하기"
}

### Todo 삭제
DELETE http://localhost:8080/todo/1

### Todo 생성 공백
POST http://localhost:8080/todo
Content-Type: application/json

{
  "title": "                               "
}