### 회원가입
POST http://localhost:8080/member
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678",
  "nickname": "tester"
}

### 로그인
POST http://localhost:8080/authCustom/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

### 로그인 사용자 확인
GET http://localhost:8080/authCustom/me

###

### 로그아웃
POST http://localhost:8080/authCustom/logout

### 게시글 생성
POST http://localhost:8080/post
Content-Type: application/json

{
  "title": "첫 번째 게시글",
  "content": "게시글 작성 테스트입니다."
}

### 게시글 단건 조회
GET http://localhost:8080/post/detail/1


### 댓글 생성
POST http://localhost:8080/comment/post/1
Content-Type: application/json

{
  "content": "첫 번째 댓글입니다.",
  "parentId": null
}

### 대댓글 생성
POST http://localhost:8080/comment/post/1
Content-Type: application/json

{
  "content": "첫 번째 대댓글입니다.",
  "parentId": 1
}

### 게시글 제목/내용 수정
PATCH http://localhost:8080/post/1
Content-Type: application/json

{
  "title": "수정된 제목",
  "content": "수정된 내용입니다."
}